import eu.europa.ec.fisheries.uvms.rules.service.business.ErrorEvent;
import eu.europa.ec.fisheries.uvms.rules.service.business.RawMovementFact;
import eu.europa.ec.fisheries.uvms.rules.service.business.RulesUtil;
import java.util.Date;

global eu.europa.ec.fisheries.uvms.rules.service.RulesService rulesService;
global org.slf4j.Logger logger;


rule "Sanity check - Latitude must exist"
dialect "java"
    when
        $fact : RawMovementFact(latitude == null)
    then
        logger.info("\t==> Executing RULE 'Sanity check - Latitude must exist'");
        $fact.setOk(false);
        insert(new ErrorEvent("Sanity check - Latitude must exist", $fact));
end

rule "Sanity check - Longitude must exist"
dialect "java"
    when
        $fact : RawMovementFact(longitude == null)
    then
        logger.info("\t==> Executing RULE 'Sanity check - Longitude must exist'");
        $fact.setOk(false);
        insert(new ErrorEvent("Sanity check - Longitude must exist", $fact));
end


rule "Create an alarm report"
dialect "java"
    when
        $e : ErrorEvent($ruleName : ruleName, $rawFact : rawFact)
    then
        logger.info("\t==> Executing RULE 'Create an alarm report'");
        rulesService.createAlarmReport($ruleName, $rawFact);
end

