import eu.europa.ec.fisheries.uvms.rules.service.business.PositionEvent;
import eu.europa.ec.fisheries.uvms.rules.service.business.ErrorEvent;

rule "Latitude must exist"
dialect "java"
    when
        $p : PositionEvent(latitude == null, $myAssetName : assetName)
    then
        System.out.println("DEBUG - Latitude is null (" + $myAssetName + ")");
        insert(new ErrorEvent($p, "latitude is null for asset " + $myAssetName));
end

rule "Longitude must exist"
dialect "java"
    when
        $p : PositionEvent(longitude == null, $myAssetName : assetName)
    then
        System.out.println("DEBUG - Longitude is null (" + $myAssetName + ")");
        insert(new ErrorEvent($p, "longitude is null for asset " + $myAssetName));
end
